version: '3.8'

services:
  optinetflow:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=${PORT}
    volumes:
      - /app/.pnpm-store/
      - /app/node_modules/
      - ./:/app
    command: sh -c "pnpm prisma:generate && pnpm start:dev"