name: Optinetflow Node.js CI

on: 
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ startsWith(github.ref, 'refs/heads/main') && 'prod' || 'stage' }}
    strategy:
      matrix:
        node-version: [18]
    steps:
    - name: 'Create env file'
      run: |
        echo "${{ env.ENV_FILE }}" > .env
    - run: echo .env


    # - uses: actions/checkout@v3
    # - uses: pnpm/action-setup@v2
    #   with:
    #     version: 8
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'pnpm'
    # - name: Install dependencies
    #   run: pnpm install
    # - run: pnpm run lint
    # - run: pnpm run build
    # - run: pnpm test
